### ISSUE TITLE
Support for Linux/Osx 

### ISSUE THREAD

**Issue by 7sharp9** [enricosada/LightTable-FSharp#2]
On Linux and Osx fsi is known as fsharpi, and fsharpc rather than fsc.

An example of fsi path detection is here: https://github.com/7sharp9/fsharpbinding/blob/master/FSharp.CompilerBinding/CompilerLocationUtils.fs#L255

**Comment by enricosada** [comment]
added mono support (tested on mac os). Like windows, fsharpi should be in PATH

@7sharp9 thx for link, i'll add smarter location default after

**Comment by 7sharp9** [comment]
If you need any help let me know, I maintain the F# language plugin for Xamarin Studio, so I can probably point you to code snippets pretty quickly :-)
